server:
  port: 8687

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 192.168.10.106:9092
    consumer:
      group-id: test-consumer-group
