server:
  port: 8070
spring:
  application:
    name: consumer-eureka
eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10  #间隔多久去拉取服务注册中心消息
  service-url:                    #对中心外暴露的地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


