server:
  port: 8091
spring:
  application:
    name: provider-eureka
eureka:
  instance:
    hostname: eureka02
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    service-url:                    #对中心外暴露的地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
