server:
  port: 8989
spring:
  mvc:
    static-path-pattern=/templates/**:
  datasource:
      url: jdbc:mysql://localhost:3306/gf_easy
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8