server:
  port: 8686

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.106
    port: 6379
    password: "123456"
    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数
  kafka:
    bootstrap-servers: 192.168.10.106:9092
