server:
  port: 8787
spring:
  data:
    mongodb:
      host: 127.0.0.1 #??MongoDB????
      port: 27017 #?????????27017
      database: test
      authentication-database: admin # ?????????
      username: root #???
      password: root #??