server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.easy.cloud.entities
eureka:
  instance:
    hostname: eureka03
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    service-url:                    #对中心外暴露的地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true