server:
  port: 8500
eureka:
  instance:
    hostname: gataway01
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    service-url:                    #对中心外暴露的地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#      routes:
#         - id: one
#           uri: lb://eureka02
#           order: 8090
#           predicates:
#             - Path=/product/**