server:
  port: 8686
spring:
  application:
    name: demo-private

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 830258d7-5bb9-49a6-8c60-6a56b75c8e08
        group: SEATA_GROUP
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver



seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: 830258d7-5bb9-49a6-8c60-6a56b75c8e08
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: 830258d7-5bb9-49a6-8c60-6a56b75c8e08

  service:
    vgroupMapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: true

